//
//  Code_Phrase_GeneratorAppDelegate.m
//  Code Phrase Generator
//
//  Created by Scott J. Roberts on 5/22/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import "Code_Phrase_GeneratorAppDelegate.h"
#include <stdlib.h>

@implementation Code_Phrase_GeneratorAppDelegate

@synthesize window;
@synthesize prefixField;
@synthesize wordlist;
@synthesize textField;

- (id) init {
	
	if ( [super init] != FALSE ) {
		self.wordlist = [NSMutableArray arrayWithObjects:   
					@"Artisan",
					@"Azure",
					@"Alpha",
					@"Bravo",
					@"Charlie",
					@"Delta",
					@"Echo",
					@"Foxtrot",
					@"Golf",
					@"Hotel",
					@"India",
					@"Juliet",
					@"Kilo",
					@"Lima",
					@"Mike",
					@"November",
					@"Oscar",
					@"Papa",
					@"Quebec",
					@"Romeo",
					@"Sierra",
					@"Tango",
					@"Uniform",
					@"Victor",
					@"Whiskey",
					@"X-ray",
					@"Yankee",
					@"Zulu",
					@"Black",
					@"Blue",
					@"Brown",
					@"Green",
					@"Indigo",
					@"Jade",
					@"Orange",
					@"Pink",
					@"Purple",
					@"Red",
					@"Violet",
					@"Yellow",
					@"Silver",
					@"Solar",
					@"Sunrise",
					@"Crescent",
					@"Relentless",
					@"Polar",
					@"Northern",
					@"Southern",
					@"Eastern",
					@"Western",
					@"Mavrick",
					@"Diesel",
					@"Cobra",
					@"Abacus",
					@"Thunder"
					@"Bright",
					@"Condor",
					@"Eclipse",
					@"Flavius",
					@"Fusion",
					@"Garden",
					@"Parabellum",
					@"Spirit",
					@"Ribbon",
					@"Vigilance",
					@"Endeavour",
					@"Atlas",
					@"Quest",
					@"Kratos",
					@"Dragon",
					@"Fast",
					@"Death",
					@"Nobel",
					@"Strike",
					@"Sabre",
					@"Ace",
					@"Command",
					@"Impairor",
					@"Ibis",
					@"Velator",
					@"Reaper",
					@"Crucifier",
					@"Executioner",
					@"Inquisitor",
					@"Magnate",
					@"Punisher",
					@"Tormentor",
					@"Bantam",
					@"Condor",
					@"Griffin",
					@"Heron",
					@"Kestrel",
					@"Merlin",
					@"Maulus",
					@"Navitas",
					@"Breacher",
					@"Burst",
					@"Rifter",
					@"Slasher",
					@"Vigil",
					@"Coercer",
					@"Catalyst",
					@"Thrasher",
					@"Cruisers",
					@"Arbitrator",
					@"Maller",
					@"Omen",
					@"Blackbird",
					@"Moa",
					@"Osprey",
					@"Thorax",
					@"Vexor",
					@"Bellicose",
					@"Rupture",
					@"Scythe",
					@"Stabber",
					@"Harbinger",
					@"Prophecy",
					@"Drake",
					@"Ferox",
					@"Brutix",
					@"Myrmidon",
					@"Cyclone",
					@"Hurricane",
					@"Abaddon",
					@"Apocalypse",
					@"Armageddon",
					@"Raven",
					@"Rokh",
					@"Scorpion",
					@"Dominix",
					@"Hyperion",
					@"Megathron",
					@"Maelstrom",
					@"Tempest",
					@"Typhoon",
					@"Retribution",
					@"Vengeance",
					@"Harpy",
					@"Hawk",
					@"Enyo",
					@"Ishkur",
					@"Jaguar",
					@"Wolf",
					@"Marauder",
					@"Paladin",
					@"Golem",
					@"Kronos",
					@"Vargur",
					@"Redeemer",
					@"Widow",
					@"Sin",
					@"Panther",
					@"Sentinel",
					@"Kitsune",
					@"Hyena",
					@"Purifier",
					@"Buzzard",
					@"Manticore",
					@"Helios",
					@"Nemesis",
					@"Cheetah",
					@"Hound",
					@"Interceptor",
					@"Crusader",
					@"Malediction",
					@"Crow",
					@"Raptor",
					@"Ares",
					@"Taranis",
					@"Claw",
					@"Stiletto",
					@"Heretic",
					@"Eris",
					@"Sabre",
					@"Onyx",
					@"Phobos",
					@"Broadsword",
					@"Sacrilege",
					@"Zealot",
					@"Cerberus",
					@"Eagle",
					@"Deimos",
					@"Ishtar",
					@"Muninn",
					@"Vagabond",
					@"Curse",
					@"Pilgrim",
					@"Falcon",
					@"Rook",
					@"Arazu",
					@"Lachesis",
					@"Huginn",
					@"Rapier",
					@"Absolution",
					@"Damnation",
					@"Nighthawk",
					@"Vulture",
					@"Astarte",
					@"Eos",
					@"Claymore",
					@"Sleipnir",
					@"Legion",
					@"Tengu",
					@"Proteus",
					@"Loki",
					@"Aeon",
					@"Archon",
					@"Chimera",
					@"Wyvern",
					@"Nyx",
					@"Thanatos",
					@"Hel",
					@"Nidhoggur",
					@"Dreadnoughts",
					@"Revelation",
					@"Phoenix",
					@"Moros",
					@"Naglfar",
					@"Titan",
					@"Avatar",
					@"Leviathan",
					@"Erebus",
					@"Ragnarok",
					@"Bestower",
					@"Sigil",
					@"Badger",
					@"Hoarder",
					@"Mammoth",
					@"Wreathe",
					@"Providence",
					@"Charon",
					@"Obelisk",
					@"Fenrir",
					@"Ark",
					@"Rhea",
					@"Anshar",
					@"Nomad",
					@"Impel",
					@"Prorator",
					@"Bustard",
					@"Crane",
					@"Occator",
					@"Viator",
					@"Mastodon",
					@"Prowler",
					@"Guardian",
					@"Basilisk",
					@"Oneiros",
					@"Scimitar",
					@"Orca",
					@"Covetor",
					@"Procurer",
					@"Retriever",
					@"Exhumer",
					@"Hulk",
					@"Mackinaw",
					@"Skiff	",
					@"Noctis	",
					@"Rorqual",
					@"Anchor",
					@"Angel",
					@"Anvil",
					@"Archer",
					@"Arrow",
					@"Aster",
					@"Badger",
					@"Bamboo",
					@"Banner",
					@"Barley",
					@"Beard",
					@"Bishop",
					@"Boar",
					@"Boy",
					@"Bracket",
					@"Bunny",
					@"Cat",
					@"Cedar",
					@"Cheese",
					@"Club",
					@"Corkscrew",
					@"Crop",
					@"Danube",
					@"Dean",
					@"Devil",
					@"Diamond",
					@"Diver",
					@"Dolphin",
					@"Drover",
					@"Duck",
					@"Duckling",
					@"Duster",
					@"Envoy",
					@"Flag",
					@"Flannel",
					@"Flash",
					@"Flax",
					@"Fox",
					@"Friend",
					@"Garland",
					@"Garlic",
					@"Gate",
					@"Ginger",
					@"Granite",
					@"Grass",
					@"Hammer",
					@"Hammock",
					@"Harvest",
					@"Hawk",
					@"Hebe",
					@"Herald",
					@"Jack",
					@"Jacket",
					@"Jay",
					@"Joker",
					@"Knight",
					@"Lemon",
					@"Light",
					@"Lizard",
					@"Mace",
					@"Maria",
					@"Mist",
					@"Moon",
					@"Neck",
					@"Nell",
					@"Palm",
					@"Parrot",
					@"Passion",
					@"Peacock",
					@"Picture",
					@"Pippin",
					@"Poodle",
					@"Possum",
					@"Prince",
					@"Putter",
					@"Queen",
					@"Rapier",
					@"Reaper",
					@"River",
					@"Rock",
					@"Rose",
					@"Rosette",
					@"Saga",
					@"Sand",
					@"Sapphire",
					@"Satin",
					@"Setter",
					@"Shoes",
					@"Shrimp",
					@"Silk",
					@"Sky",
					@"Slug",
					@"Snow",
					@"Sparkler",
					@"Star",
					@"Steel",
					@"Steer",
					@"Stone",
					@"Streak",
					@"Study",
					@"Sugar",
					@"Sun",
					@"Tartan",
					@"Temple",
					@"Ticket",
					@"Top",
					@"Tulip",
					@"Vesta",
					@"Vision",
					@"Vixen",
					@"Walnut",
					@"Water",
					@"Water",
					@"Willow",
					@"Wizard",
					@"Yeoman", 
					nil];
		
		//[wordlist sortUsingSelector:@selector(compare:)];
	}
	
	return self;
}

- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
	
	textField.stringValue = [self generatePhrases];
}

- (IBAction) displayCodePhrase:(id)sender {
	
	textField.stringValue = [self generatePhrases];
}

- (NSString*) generateWord{
	return [[wordlist objectAtIndex:arc4random() % [wordlist count]] autorelease];
}

- (NSString*) generatePhrase {
	
	NSString* word1;
		
	if ( [prefixField.stringValue isEqualToString:@""] ) {
		word1 = [[self generateWord] autorelease];
	} else {
		word1 = prefixField.stringValue;
	}

	NSString* word2 = [self generateWord];
	
	NSString* newPhrase = [word1 stringByAppendingFormat:@" %@", word2];
	
	[word2 autorelease];
	
	return [newPhrase autorelease];
}

- (NSString*) generatePhrases {
	
	NSMutableString* phrases = [[NSMutableString alloc] initWithString:@""];
	
	for(int i=0; i < 10; i++){
		
		[phrases appendFormat:@"%@\n", [self generatePhrase]];
	}
	
	return phrases;
}

@end
